Server:
  Name: "DouYinAPIServer"
  Address: "172.21.146.253"
  Port: 8088

Hertz:
  UseNetpoll: true
  Http2: 
    Enable: false
    DisableKeepalive: false
    ReadTimeout: "1m0s"
  Tls: 
    Enable: false
    CertFile: ""
    KeyFile: ""
    ALPN: true