mysql:
  dsn: "root:Aa1076766987@tcp(127.0.0.1:3306)/tiktok?charset=utf8mb4&parseTime=True&loc=Local"

redis:
  addr: "127.0.0.1:6379"
  password: "Aa1076766987"
  poolSize: 30
  minConns: 30
  followersdb: 0
  followingdb: 1
  friendsdb: 2
  userdb: 3
  commentdb: 4
  videodb: 5
  favoritedb: 6
  exipretime: "48h"

rpc:
  comment:
    psm: "bytecamp.douyin.comment"
  favorite:
    psm: "bytecamp.douyin.favorite"
  relation:
    psm: "bytecamp.douyin.relation"
  user:
    psm: "bytecamp.douyin.user"
  video:
    psm: "bytecamp.douyin.video"
  message:
    psm: "bytecamp.douyin.message"