mysql:
  dsn: "root:Aa1076766987@tcp(81.70.207.243:3306)/tiktok?charset=utf8mb4&parseTime=True&loc=Local"

redis:
  addr: "81.70.207.243:6379"
  password: "Aa1076766987"
  poolSize: 30
  minConns: 30
  followersdb: 0
  followingdb: 1
  friendsdb: 2
  userdb: 3

oss:
  endpoint: "oss-cn-beijing.aliyuncs.com"
  ak: "LTAI5tPgCbMia8qwAy2xesdP"
  sk: "5F3lX57hEguOpYXtM2C9fEGuyUQ4VP"
  videobucket: "bytecampvideo"
  imagebucket: "bytecampimage"